# Etapa 1: build da app
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: servir com nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

# Copia um nginx.conf customizado (opcional)
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]