services:
  clinica_app:
    container_name: clinica_app
    image: inf24dw1g32/node:latest
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 12345678
      DB_NAME: Scheduler
    depends_on:
      db:
        condition: service_healthy
    networks:
      - scheduler-network

  clinica_web:    
    image: inf24dw1g32/react:latest
    container_name: clinica_web
    ports:
      - "80:80"
    networks:
      - scheduler-network

  db:
    container_name: scheduler_db
    image: inf24dw1g32/mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: Scheduler
      LANG : C.UTF-8
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 25s
      timeout: 5s
      retries: 5
      start_period: 150s
    networks:
      - scheduler-network

networks:
  scheduler-network:
    driver: bridge

